//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.examen.t456.Modelo
{
    using dam.di.examen.t456.MVVM;
    using System;
    using System.Collections.Generic;
    
    public partial class artista : MVBase
    {
        public artista()
        {
            this.pertenece = new HashSet<pertenece>();
        }
    
        public string dni { get; set; }
        public string nombre { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<pertenece> pertenece { get; set; }
    }
}
