//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.examen.t456.Modelo
{
    using dam.di.examen.t456.MVVM;
    using System;
    using System.Collections.Generic;
    
    public partial class companyia : MVBase
    {
        public companyia()
        {
            this.disco = new HashSet<disco>();
        }
    
        public int cod { get; set; }
        public string nombre { get; set; }
        public string dir { get; set; }
        public string fax { get; set; }
        public string tfno { get; set; }
    
        public virtual ICollection<disco> disco { get; set; }
    }
}
