//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.examen.t456.Modelo
{
    using dam.di.examen.t456.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class disco : MVBase
    {
        public disco()
        {
            this.cancion = new HashSet<cancion>();
        }
    
        public int cod { get; set; }
        [Required]
        [MaxLength(30, ErrorMessage = "La longitud maxima es de 30 caracteres")]
        [MinLength(4, ErrorMessage = "La longitud mínima es de 4 caracteres")]
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int cod_comp { get; set; }
        public int cod_gru { get; set; }
        [Required]
        public virtual companyia companyia { get; set; }
        [Required]
        public virtual grupo grupo { get; set; }
        public virtual ICollection<cancion> cancion { get; set; }
    }
}
