//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.examen.t456.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class musicaEntities : DbContext
    {
        public musicaEntities()
            : base("name=musicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<artista> artista { get; set; }
        public DbSet<cancion> cancion { get; set; }
        public DbSet<club> club { get; set; }
        public DbSet<companyia> companyia { get; set; }
        public DbSet<disco> disco { get; set; }
        public DbSet<grupo> grupo { get; set; }
        public DbSet<pertenece> pertenece { get; set; }
    }
}
