//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen.dam.di._21.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class avion
    {
        public avion()
        {
            this.revisiones = new HashSet<revisiones>();
            this.vuelos = new HashSet<vuelos>();
        }
    
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Any_Fabricacion { get; set; }
        public string Clase { get; set; }
    
        public virtual tipo tipo { get; set; }
        public virtual ICollection<revisiones> revisiones { get; set; }
        public virtual ICollection<vuelos> vuelos { get; set; }
    }
}
