//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen.dam.di._21.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aerolineasEntities : DbContext
    {
        public aerolineasEntities()
            : base("name=aerolineasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<avion> avion { get; set; }
        public DbSet<ciudades> ciudades { get; set; }
        public DbSet<personal> personal { get; set; }
        public DbSet<revisiones> revisiones { get; set; }
        public DbSet<tipo> tipo { get; set; }
        public DbSet<vuelos> vuelos { get; set; }
    }
}
