//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen.dam.di._21.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public personal()
        {
            this.vuelos = new HashSet<vuelos>();
        }
    
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string CogNombres { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Cargo { get; set; }
    
        public virtual ICollection<vuelos> vuelos { get; set; }
    }
}
