//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.inventario.clase.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public articulo()
        {
            this.salida = new HashSet<salida>();
            this.articulo1 = new HashSet<articulo>();
        }
    
        public int idarticulo { get; set; }
        public string numserie { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public Nullable<int> usuarioalta { get; set; }
        public Nullable<int> usuariobaja { get; set; }
        public int modelo { get; set; }
        public Nullable<int> departamento { get; set; }
        public int espacio { get; set; }
        public Nullable<int> dentrode { get; set; }
        public string observaciones { get; set; }
    
        public virtual ICollection<salida> salida { get; set; }
        public virtual ICollection<articulo> articulo1 { get; set; }
        public virtual articulo articulo2 { get; set; }
        public virtual departamento departamento1 { get; set; }
        public virtual espacio espacio1 { get; set; }
        public virtual modeloarticulo modeloarticulo { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
