//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.inventario.clase.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diinventarioEntities : DbContext
    {
        public diinventarioEntities()
            : base("name=diinventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<articulo> articulo { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<espacio> espacio { get; set; }
        public DbSet<ficheromodelo> ficheromodelo { get; set; }
        public DbSet<ficherousuario> ficherousuario { get; set; }
        public DbSet<grupo> grupo { get; set; }
        public DbSet<modeloarticulo> modeloarticulo { get; set; }
        public DbSet<permiso> permiso { get; set; }
        public DbSet<permisosrol> permisosrol { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<salida> salida { get; set; }
        public DbSet<tipoarticulo> tipoarticulo { get; set; }
        public DbSet<tipousuario> tipousuario { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
