//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.inventario.clase.Modelo
{
    using dam.di.inventario.clase.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class modeloarticulo : MVBase
    {
        public modeloarticulo()
        {
            this.articulo = new HashSet<articulo>();
            this.ficheromodelo = new HashSet<ficheromodelo>();
        }
    
        public int idmodeloarticulo { get; set; }
        [Required]
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual ICollection<articulo> articulo { get; set; }
        public virtual ICollection<ficheromodelo> ficheromodelo { get; set; }
        [Required]
        public virtual tipoarticulo tipoarticulo { get; set; }
    }
}
