//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.inventario.clase.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisosrol
    {
        public int idpermisosrol { get; set; }
        public int rol { get; set; }
        public int permiso { get; set; }
        public Nullable<int> acceso { get; set; }
    
        public virtual permiso permiso1 { get; set; }
        public virtual rol rol1 { get; set; }
    }
}
