//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.inventario.clase.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida
    {
        public int idsalida { get; set; }
        public int usuario { get; set; }
        public int articulo { get; set; }
        public System.DateTime fechasalida { get; set; }
        public Nullable<System.DateTime> fechadevolucion { get; set; }
    
        public virtual articulo articulo1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
