//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.inventario.clase.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoarticulo
    {
        public tipoarticulo()
        {
            this.modeloarticulo = new HashSet<modeloarticulo>();
            this.tipoarticulo1 = new HashSet<tipoarticulo>();
        }
    
        public int idtipoarticulo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> padre { get; set; }
    
        public virtual ICollection<modeloarticulo> modeloarticulo { get; set; }
        public virtual ICollection<tipoarticulo> tipoarticulo1 { get; set; }
        public virtual tipoarticulo tipoarticulo2 { get; set; }
    }
}
