//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.repaso.navidad.ham.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.pagos = new HashSet<pagos>();
            this.pedidos = new HashSet<pedidos>();
        }
    
        public int CodigoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string NombreContacto { get; set; }
        public string ApellidoContacto { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string LineaDireccion1 { get; set; }
        public string LineaDireccion2 { get; set; }
        public string Ciudad { get; set; }
        public string Region { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> CodigoEmpleadoRepVentas { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual ICollection<pagos> pagos { get; set; }
        public virtual ICollection<pedidos> pedidos { get; set; }
    }
}
