//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.repaso.navidad.ham.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int CodigoCliente { get; set; }
        public string FormaPago { get; set; }
        public string IDTransaccion { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
