//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.repaso.navidad.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallepedidos
    {
        public int CodigoPedido { get; set; }
        public string CodigoProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnidad { get; set; }
        public short NumeroLinea { get; set; }
    
        public virtual pedidos pedidos { get; set; }
        public virtual productos productos { get; set; }
    }
}
