//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam.di.repaso.navidad.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public pedidos()
        {
            this.detallepedidos = new HashSet<detallepedidos>();
        }
    
        public int CodigoPedido { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public System.DateTime FechaEsperada { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Estado { get; set; }
        public string Comentarios { get; set; }
        public int CodigoCliente { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual ICollection<detallepedidos> detallepedidos { get; set; }
    }
}
